### ISSUE TITLE
About the setup

### ISSUE THREAD

**Issue by bigsheep2012** [Forceflow/trimesh2#1]
Hi Jeroen,

Thank you for the works.

I am pretty new to Trimesh2. Could you please tell me how to setup trimesh2 in Visual Studio 2015?
(e.g., if I have an empty Win32 console project, what should I do to use trimesh2 features?)

Looking forward to your reply.

Best regards,
Lin

**Comment by Forceflow** [comment]
First, build the Trimesh2 project on your computer using the Visual Studio Project in `\trimesh2\msvc\vs2015`. Building it in Release and Debug mode should create folders in the main trimesh2 folder named `lib.Win64.vs140`(64 bit) and `lib.Win32.vs140` (32-bit). In these folders will be the static libraries for Trimesh, `trimesh.lib` and `trimeshd.lib`.

To use TriMesh2 in your project, make sure you **include** the `include\TriMesh.h` file, and make sure your **linker** can find either `trimesh.lib` (for Release builds) or `trimeshd.lib` (for Debug builds).

For an example, check the mesh_view project in `trimesh2\msvc\vs2015\mesh_view`. This is an utility from the original TriMesh2 project which is now built using VS 2015. Your own project should have a similar setup.

**Comment by bigsheep2012** [comment]
Thank you very much.

Lin

**Comment by Forceflow** [comment]
No problem!
