### ISSUE TITLE
Is "utils/mesh_align.exe" use the method presented in paper named: "A Symmetric Objective Function for ICP"?

### ISSUE THREAD

**Issue by ghost** [Forceflow/trimesh2#15]
I want to make sure that whether "utils/mesh_align.exe" use the method presented in paper named: "[A Symmetric Objective Function for ICP](https://pixl.cs.princeton.edu/pubs/Rusinkiewicz_2019_ASO/index.php)"?

If not, how can I use the method in the paper?

Thanks for your splendid work! It's very helpful.

**Comment by Forceflow** [comment]
As I mention in the README, this is code written by Szymon Rusinkiewicz. Since that's his paper, I would presume the code is following that structure.

**Comment by ghost** [comment]
OK, thanks a lot.
