### ISSUE TITLE
error LNK2038 when trying to use this lib

### ISSUE THREAD

**Issue by francescobrischetto** [Forceflow/trimesh2#19]
Hello,
I'm having some linker issues in using this library. Any suggest on how to fix it?
Sorry if I am not in the right place to ask.

![errors](https://user-images.githubusercontent.com/28810769/164685076-54c5df2f-d6d6-40da-8fb3-b0a5df8537c9.jpg)

**Comment by Forceflow** [comment]
My Italian is not great, but I think you're trying to dynamically link the library, while you should statically link it?

**Comment by francescobrischetto** [comment]
I finally fixed it. It was my fault on compiling the library with the wrong  linker options. Thanks and sorry, you can just remove this thread

**Comment by Forceflow** [comment]
No problem. Is there any way I can improve the documentation to prevent this in the future?

**Comment by francescobrischetto** [comment]
Well, my problem was that I tried to insert the library in an environment that was not setupped by me (but from my teacher) and so I didn't know actually what exactly was going on. Moreover, when tried to compile the library myself, with the Visual Studio build solutions that you provided, it was automatically set the flag /MD instead of the flag /MT that I'm using in my project (and I didn't know the difference here reported: https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-170 ). Maybe my was only a really specific case
