### ISSUE TITLE
Strange translation results.

### ISSUE THREAD

**Issue by perrykipkerrie** [Forceflow/trimesh2#3]
Hi Forceflow, 

Firstly thank you for the great fork!

I think i've bug in the ICP algorithm. 

With certain objects, when they are located over eachother, the translation get messed up, and the resulting transformation matrix will cause the object jump to the other side of the screen. 
The resulting rotation matrix is perfect, but it is the translation that is causing trouble. 

Its not present in all cases, but in the teeth (which are attached) the phenomenon is present.

What do you think about this?

[testset.zip](https://github.com/Forceflow/trimesh2/files/1723332/testset.zip)

**Comment by Forceflow** [comment]
I'm not overly familiar with the ICP algorithm. Have you tried switching between a 32-bit and 64-bit build, just to see if that makes any difference? They *should* produce the same results, but you never know.

**Comment by perrykipkerrie** [comment]
Thank you for your quick reply.

I've used the 32bits, but it gives the same results.

**Comment by Forceflow** [comment]
@perrykipkerrie The ICP stuff got an overhaul in the latest Trimesh2 release, from upstream.
Closing this, create a new issue if you still think there's something whack about the implementation.
